// Mocks generated by Mockito 5.4.0 from annotations
// in hris_mock/test/presentation/employee_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:hris_mock/common/state_enum.dart' as _i5;
import 'package:hris_mock/domain/entities/employee.dart' as _i4;
import 'package:hris_mock/domain/usecase/get_employee.dart' as _i2;
import 'package:hris_mock/presentation/provider/employee_list_notifier.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetEmployee_0 extends _i1.SmartFake implements _i2.GetEmployee {
  _FakeGetEmployee_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EmployeeListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmployeeListNotifier extends _i1.Mock
    implements _i3.EmployeeListNotifier {
  MockEmployeeListNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetEmployee get getEmployee => (super.noSuchMethod(
        Invocation.getter(#getEmployee),
        returnValue: _FakeGetEmployee_0(
          this,
          Invocation.getter(#getEmployee),
        ),
      ) as _i2.GetEmployee);

  @override
  set getEmployee(_i2.GetEmployee? _getEmployee) => super.noSuchMethod(
        Invocation.setter(
          #getEmployee,
          _getEmployee,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i4.Employee> get employeeList => (super.noSuchMethod(
        Invocation.getter(#employeeList),
        returnValue: <_i4.Employee>[],
      ) as List<_i4.Employee>);

  @override
  _i5.RequestState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i5.RequestState.initial,
      ) as _i5.RequestState);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: '',
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> fetchEmployee() => (super.noSuchMethod(
        Invocation.method(
          #fetchEmployee,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
